alias sudo='sudo '                  # makes sudo work with aliases

# Simple mappings
alias p='pwd'
alias c='clear'
alias v='vim'
alias py='python'
alias py3='python3.3'
alias rm='rm -I'                    # safer remove

# ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Git
alias gc='git commit -m '
alias gs='git status'

